---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-service-ca
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-ca
  namespace: kubernetes-service-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-ca
  namespace: kubernetes-service-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-ca
subjects:
- kind: ServiceAccount
  name: service-ca
  namespace: kubernetes-service-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-ca
  namespace: kubernetes-service-ca
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - update
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-ca
subjects:
- kind: ServiceAccount
  name: service-ca
  namespace: kubernetes-service-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-ca
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernetes-service-ca
  name: service-ca
  labels:
    app: service-ca
    service-ca: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-ca
      service-ca: "true"
  template:
    metadata:
      name: service-ca
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: restricted-v2
      labels:
        app: service-ca
        service-ca: "true"
    spec:
      serviceAccountName: service-ca
      containers:
      - name: service-ca-controller
        image: quay.io/ykoer/service-ca-operator:latest
        imagePullPolicy: IfNotPresent
        command: ["service-ca-operator", "controller"]
        ports:
        - containerPort: 8443
        securityContext:
          runAsNonRoot: false
        resources:
          requests:
            memory: 120Mi
            cpu: 10m
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/secrets/signing-key
          name: signing-key
        - mountPath: /var/run/configmaps/signing-cabundle
          name: signing-cabundle
      volumes:
      - name: signing-key
        secret:
          secretName: signing-key
      - name: signing-cabundle
        configMap:
          name: signing-cabundle
---
apiVersion: v1
kind: Secret
metadata:
  name: signing-key
  namespace: kubernetes-service-ca
type: kubernetes.io/tls
stringData:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIUUCugJV493oJRUx6q3ayN8ma9OokwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEfMB0GA1UEAwwWc2VydmljZS1zZXJ2
    aW5nLXNpZ25lcjAeFw0yNDA1MDgyMTU2MTZaFw0zNDA1MDYyMTU2MTZaMGYxCzAJ
    BgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5l
    dCBXaWRnaXRzIFB0eSBMdGQxHzAdBgNVBAMMFnNlcnZpY2Utc2VydmluZy1zaWdu
    ZXIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCeQNAp8b/jrMO/0xRa
    APsKjm0I0F1QTgMFJTihJ63Jmc+NHxxe7cXXS/6enyKrkp1OOGF2ip/L/65HEXOj
    psttmm6y2GXqZd3NpsyT5Pv4R9V+xphHxJL21zr4jgCsmoV8ZfjtgtwC5s2LeYuT
    4+2pQiKA1cwEWUcjr657s6LkgRvpuNbPtFR4gAmD/v3IWbr5JVkk19jwduLpyXKb
    plz5wa9VPLD7qXrFDmvND9PfL3QtDGiy1SmR23ndLiNkXaX5mTEdHNhuPznNVA03
    TUUnNKKbUTe8EtfVWQKTMP21NhXsvXjfHDMzPIbvKtOnxIEft5ePTXuU4PwixyCR
    uuKQRaL/5doCqXovAy1ED4HIz/yIWEq1I++MXJNF48bKcLQiIZcwuDbibRcTv31U
    tRN2YWYngaNoGTQ+2SdHwqbpXQe2dhUyoNREsC3FOySUd5khoUsvRvMujqV7e68t
    f5gt+0JMmNZTfDjbFSSix/GTIXBEp4PwOX3V8bUIs88xA3NFtbVoH531trOH6GCq
    ldTaUrZoFO3y6bQHgDH1Va5BbWSQ932L+cjE1VnYztLwN4VjmQ0uqim76cUNY7u9
    TljvMyXF40PROyygFf63CKn3aT42Fdkhl1I/XL13aPeONZDeYp/u/vKAxE7E3RSd
    RGZQSUzmhUrdwqbAuIq4Sjp1QQIDAQABo1MwUTAdBgNVHQ4EFgQUx21sv0K7gWyI
    /5eNkzolrkyvqZEwHwYDVR0jBBgwFoAUx21sv0K7gWyI/5eNkzolrkyvqZEwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEADvaVsoujcqxxF1zr+YnZ
    6lP5EUe2ABOf8rGrFGePm6qpK6Lr7t2Kx3PJVa6JxUzzW5zRxHjBrVvJMzj6QDxf
    wGvdWTHK2GHZ7bbKCALSl1/eKRPrJmPwPLlkCnSFjQjiF8vtCFoPbHHtF23nctAc
    RUZP5LK+jrDJh6EUmNRRPdyv9NVsjKYpQowQHdv7MKjfkiy2rt0WysfXc8fW4XNq
    EbKhRZLsbzlF+kNVlPW/8vFwEBJVvI5+ysWY/L3xb05vO6JKWrWQlJ5bH1BcMxo6
    MccQA7t04XzR+u4aX1rHxAsxnc9JNgPw5LSbyN7M4pE9J9pi2F5gGlyvltL1JSDg
    JHrLcOpwIrXuKGD1pDk8vBHzz8xuQT+VOb1lBRXO61XK5Q8olEqy9jErEjIRYLOb
    IXW8+FcTJrnV1IjUZbpW3GP4kRGlwgwEmMM/ggHbT98FQbmO1Aaa4ArETZilfjfY
    KUsVuSRgU0BY8Kkq18dI/qvBngebV/CECnyDb98FUYhOAwuJF+vSmS9HSBXzyrnw
    axyuUu1YupBn4stOXzll2Z7BimBTVNL0FdKDWFowDmDF6jS8F1Cx7AGNOrSLYeYm
    pmRX+bjYxZo50mEgJVQ05OfIdLFfpst2gmiAiLauIqjlzKvNhYUerD3Y9cPKkt8O
    i22gbUKbDS+YWXa8GPPObZU=
    -----END CERTIFICATE-----
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIUUCugJV493oJRUx6q3ayN8ma9OokwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEfMB0GA1UEAwwWc2VydmljZS1zZXJ2
    aW5nLXNpZ25lcjAeFw0yNDA1MDgyMTU2MTZaFw0zNDA1MDYyMTU2MTZaMGYxCzAJ
    BgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5l
    dCBXaWRnaXRzIFB0eSBMdGQxHzAdBgNVBAMMFnNlcnZpY2Utc2VydmluZy1zaWdu
    ZXIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCeQNAp8b/jrMO/0xRa
    APsKjm0I0F1QTgMFJTihJ63Jmc+NHxxe7cXXS/6enyKrkp1OOGF2ip/L/65HEXOj
    psttmm6y2GXqZd3NpsyT5Pv4R9V+xphHxJL21zr4jgCsmoV8ZfjtgtwC5s2LeYuT
    4+2pQiKA1cwEWUcjr657s6LkgRvpuNbPtFR4gAmD/v3IWbr5JVkk19jwduLpyXKb
    plz5wa9VPLD7qXrFDmvND9PfL3QtDGiy1SmR23ndLiNkXaX5mTEdHNhuPznNVA03
    TUUnNKKbUTe8EtfVWQKTMP21NhXsvXjfHDMzPIbvKtOnxIEft5ePTXuU4PwixyCR
    uuKQRaL/5doCqXovAy1ED4HIz/yIWEq1I++MXJNF48bKcLQiIZcwuDbibRcTv31U
    tRN2YWYngaNoGTQ+2SdHwqbpXQe2dhUyoNREsC3FOySUd5khoUsvRvMujqV7e68t
    f5gt+0JMmNZTfDjbFSSix/GTIXBEp4PwOX3V8bUIs88xA3NFtbVoH531trOH6GCq
    ldTaUrZoFO3y6bQHgDH1Va5BbWSQ932L+cjE1VnYztLwN4VjmQ0uqim76cUNY7u9
    TljvMyXF40PROyygFf63CKn3aT42Fdkhl1I/XL13aPeONZDeYp/u/vKAxE7E3RSd
    RGZQSUzmhUrdwqbAuIq4Sjp1QQIDAQABo1MwUTAdBgNVHQ4EFgQUx21sv0K7gWyI
    /5eNkzolrkyvqZEwHwYDVR0jBBgwFoAUx21sv0K7gWyI/5eNkzolrkyvqZEwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEADvaVsoujcqxxF1zr+YnZ
    6lP5EUe2ABOf8rGrFGePm6qpK6Lr7t2Kx3PJVa6JxUzzW5zRxHjBrVvJMzj6QDxf
    wGvdWTHK2GHZ7bbKCALSl1/eKRPrJmPwPLlkCnSFjQjiF8vtCFoPbHHtF23nctAc
    RUZP5LK+jrDJh6EUmNRRPdyv9NVsjKYpQowQHdv7MKjfkiy2rt0WysfXc8fW4XNq
    EbKhRZLsbzlF+kNVlPW/8vFwEBJVvI5+ysWY/L3xb05vO6JKWrWQlJ5bH1BcMxo6
    MccQA7t04XzR+u4aX1rHxAsxnc9JNgPw5LSbyN7M4pE9J9pi2F5gGlyvltL1JSDg
    JHrLcOpwIrXuKGD1pDk8vBHzz8xuQT+VOb1lBRXO61XK5Q8olEqy9jErEjIRYLOb
    IXW8+FcTJrnV1IjUZbpW3GP4kRGlwgwEmMM/ggHbT98FQbmO1Aaa4ArETZilfjfY
    KUsVuSRgU0BY8Kkq18dI/qvBngebV/CECnyDb98FUYhOAwuJF+vSmS9HSBXzyrnw
    axyuUu1YupBn4stOXzll2Z7BimBTVNL0FdKDWFowDmDF6jS8F1Cx7AGNOrSLYeYm
    pmRX+bjYxZo50mEgJVQ05OfIdLFfpst2gmiAiLauIqjlzKvNhYUerD3Y9cPKkt8O
    i22gbUKbDS+YWXa8GPPObZU=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCeQNAp8b/jrMO/
    0xRaAPsKjm0I0F1QTgMFJTihJ63Jmc+NHxxe7cXXS/6enyKrkp1OOGF2ip/L/65H
    EXOjpsttmm6y2GXqZd3NpsyT5Pv4R9V+xphHxJL21zr4jgCsmoV8ZfjtgtwC5s2L
    eYuT4+2pQiKA1cwEWUcjr657s6LkgRvpuNbPtFR4gAmD/v3IWbr5JVkk19jwduLp
    yXKbplz5wa9VPLD7qXrFDmvND9PfL3QtDGiy1SmR23ndLiNkXaX5mTEdHNhuPznN
    VA03TUUnNKKbUTe8EtfVWQKTMP21NhXsvXjfHDMzPIbvKtOnxIEft5ePTXuU4Pwi
    xyCRuuKQRaL/5doCqXovAy1ED4HIz/yIWEq1I++MXJNF48bKcLQiIZcwuDbibRcT
    v31UtRN2YWYngaNoGTQ+2SdHwqbpXQe2dhUyoNREsC3FOySUd5khoUsvRvMujqV7
    e68tf5gt+0JMmNZTfDjbFSSix/GTIXBEp4PwOX3V8bUIs88xA3NFtbVoH531trOH
    6GCqldTaUrZoFO3y6bQHgDH1Va5BbWSQ932L+cjE1VnYztLwN4VjmQ0uqim76cUN
    Y7u9TljvMyXF40PROyygFf63CKn3aT42Fdkhl1I/XL13aPeONZDeYp/u/vKAxE7E
    3RSdRGZQSUzmhUrdwqbAuIq4Sjp1QQIDAQABAoICABR2c1Q7ybZXVGJn7qBACItS
    D6A4TRtBUxult0pYoUdJp7BAPxYOmb/f4uHA2FCmHx1fpfPtiIHDeFYBLYTnit4L
    viz1qqFMoF8N+92ob2T9vjSWhQH2qugsZsLVSG9edaHjD5/VMBIB+mmtWD0nF50v
    YNsW32Vf4+vQiiJoVR5F4YWZsdEJU3OCCXjzY6kLN+WCYkykymI22oV6AmNE9427
    RoAiM7ephPyZA5sa5P2yxaC+PjAtkaKmEKkRumApHyPZ8/inOQccZCLRhPn1za98
    RgWzp/NziPax0TxAyqAqs7AObzmDjHf0vMqNLPFrCSVAQzfeQCYSkhevIYjRHlLE
    WL/bHyt3GnX+m7YyuqLW9h+PO0ei7pqMBJEgMEA2+Cbl4cqGnx5T/uPfx1eX1sho
    INFrZm5nLx0LfVlCYdR8AzGZgcTvBAA1091Ie5eRCuNtzi9eFo/AH/DfZP0iJJgf
    e99FvbwbmFJY9O3mwK/YYLp8/ecbDVz1EuPLgXse87GLUKy3K9Y5E0+he7+PWFSa
    AU+1iyCfTRYs5LZ0mLGETeHxrQZrafcimzcQYg+HcNPtiMgrJIAPuL2Osab2YcRF
    93em1qzjUWg/EGTzMFZADafwnSuj243M28mQTQ5o1ncZpq59O5H2olI8LbbWoUSW
    /9DyF2zcOngpKgVdns5fAoIBAQDKI9l/cXux063NHy8B/70+Vutvc+RhOp2+HLXt
    PxNwmh2Kv/+SZLoFKGxmgZQqt4gX5tFoi2viYpex6gKjgjMslVfb+FhhduvsZETi
    UYWy+aeDgXtN8jiGs7vRK1cfNwBgjQEuOpzGJeVIcfQIQdRfwjMT6ShW/5GLWSyC
    CbTIDpHv/tqo8h6KYkxl2m+hNbXD+7skhDtQE20QiIoUxrsn6mMqksfLmwVrcIa/
    mj6HprXn/ZmHHx1oxsoyW975nKSnziAZqb0ozoidPqA7wdaZZfOF15Ejm9IE/osC
    3oamPoFgMUEfDS2hC47VqOkLghevBkaZ0OBkB0jN+OALwbyHAoIBAQDIa2bpQ8zJ
    zgQH+CLI5bGtgExvl+DHwSrl9yorZ8vjfLs5ekKpa0aoRZSP8Wd6PbbDyeBw0P+5
    mvOpIMzV8XSNyywBUn8KpWT+pyzOrOGqkt2My03OXDavCDg2OlT4ZEqwSwFDjqmq
    dzeOo67QUv/HzNiYSlXI87s5wlmFgj1/wgjTqIEXp+gK71E/KnpSdeiTmwouEgOd
    QuOiYb8doBSrNe2g9pXduCLBX1BE48xPwfp6amqRqdZE1P98QeVeZ9so9oklDRbL
    u+PeqF/Mj40D8uerUTGagC+xY8TL7NoWdmZpRFOKc5r60EScLwcck7TM/tA81Fe3
    aJyEG9xacLn3AoIBAD5g0b2CR6mYqQmjld4IDV4vdHfwS4m1jPgd5AZScK1O4c7v
    cO68JqtwzgLT+eU0vcqib/zTCXfS9PzyOd47T49yhqpa+Osax7MrPhaZEakpYYgz
    bNmg5dCrpknmFfyL/JHO8Y5SiA6doyO4BpaFugPS6fA7AzfVphRacGGwnRkfZemp
    u9Bm5wXNT8YeolQdPvo7tISQSb1sQTvY5sOCkD7BFdkNcppiPEnrb6mw75rs1zXA
    DKCl+W1b6wmfUC+3Jxihg0ZoGvd8xKvBp7DJIHA2BfBHlYJnk2f3JO69vM+Qelw0
    1uO+LVaFOo60kTX771MTnLXav2Qe21i0dG8sWgECggEAIu4FC5aTdICBV1o5xcWy
    h8iaicBwnp/d+CJxqQr4D/fHMadLQve9YsptsACkxjtHRSxD/6WNTC3jVZCv4oGo
    jKXiT4CvP42/4loEhyi+U9ow3r74GoUbyrmmAl18PaZNFhicacfNbjZE6olAiHJO
    veXHwhMCjHleIhzrOUePrFqG60ys4xCScoVvJZEjrId8N22IAquFEb18qupaQrGJ
    qKVHeww+5luXQxh3huoky6nFG9y8IhL1kx2EQYXCkgeLvMHq+Rgk5vEiL8YsnBxQ
    uWV2VvdZq9G3fjUjMV9gSxXrl2EfJjwrwJbXvli75pEfq7KlXFStzPtge+3XI7QN
    1QKCAQAohKm3XBQzsZViMcwIHSzOC/5nI/pZTpIXTj8uO98z/FZhDhoNejqlvMmx
    RioM/Vu+/OPMWwvjiir7fi3ECdbOFKq6FxPYeo/UGh3b8mE51pAIg0MjcNthZeL0
    BOeF9/w7o5cdIN8uaJKxHj9tBbnF94rw5lMX8DwfVNHMslCJZilHCOiJ8IxYtbj9
    yT2tpuCkflPg37RQwP47wOPKPkgxayIOD2V50vzrqhPgi/UwBCDzv6OJCOtK/xEj
    vAKqnbrpVurh6ibhGUfu3mpFjWuLhTZ2H+6DLH62GE4jDn5JkEsXtwwFRDnZMt5+
    60GrRqzlY1be5F/5tgFDk9Gl2Wtw
    -----END PRIVATE KEY-----
---
apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIUUCugJV493oJRUx6q3ayN8ma9OokwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEfMB0GA1UEAwwWc2VydmljZS1zZXJ2
    aW5nLXNpZ25lcjAeFw0yNDA1MDgyMTU2MTZaFw0zNDA1MDYyMTU2MTZaMGYxCzAJ
    BgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5l
    dCBXaWRnaXRzIFB0eSBMdGQxHzAdBgNVBAMMFnNlcnZpY2Utc2VydmluZy1zaWdu
    ZXIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCeQNAp8b/jrMO/0xRa
    APsKjm0I0F1QTgMFJTihJ63Jmc+NHxxe7cXXS/6enyKrkp1OOGF2ip/L/65HEXOj
    psttmm6y2GXqZd3NpsyT5Pv4R9V+xphHxJL21zr4jgCsmoV8ZfjtgtwC5s2LeYuT
    4+2pQiKA1cwEWUcjr657s6LkgRvpuNbPtFR4gAmD/v3IWbr5JVkk19jwduLpyXKb
    plz5wa9VPLD7qXrFDmvND9PfL3QtDGiy1SmR23ndLiNkXaX5mTEdHNhuPznNVA03
    TUUnNKKbUTe8EtfVWQKTMP21NhXsvXjfHDMzPIbvKtOnxIEft5ePTXuU4PwixyCR
    uuKQRaL/5doCqXovAy1ED4HIz/yIWEq1I++MXJNF48bKcLQiIZcwuDbibRcTv31U
    tRN2YWYngaNoGTQ+2SdHwqbpXQe2dhUyoNREsC3FOySUd5khoUsvRvMujqV7e68t
    f5gt+0JMmNZTfDjbFSSix/GTIXBEp4PwOX3V8bUIs88xA3NFtbVoH531trOH6GCq
    ldTaUrZoFO3y6bQHgDH1Va5BbWSQ932L+cjE1VnYztLwN4VjmQ0uqim76cUNY7u9
    TljvMyXF40PROyygFf63CKn3aT42Fdkhl1I/XL13aPeONZDeYp/u/vKAxE7E3RSd
    RGZQSUzmhUrdwqbAuIq4Sjp1QQIDAQABo1MwUTAdBgNVHQ4EFgQUx21sv0K7gWyI
    /5eNkzolrkyvqZEwHwYDVR0jBBgwFoAUx21sv0K7gWyI/5eNkzolrkyvqZEwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEADvaVsoujcqxxF1zr+YnZ
    6lP5EUe2ABOf8rGrFGePm6qpK6Lr7t2Kx3PJVa6JxUzzW5zRxHjBrVvJMzj6QDxf
    wGvdWTHK2GHZ7bbKCALSl1/eKRPrJmPwPLlkCnSFjQjiF8vtCFoPbHHtF23nctAc
    RUZP5LK+jrDJh6EUmNRRPdyv9NVsjKYpQowQHdv7MKjfkiy2rt0WysfXc8fW4XNq
    EbKhRZLsbzlF+kNVlPW/8vFwEBJVvI5+ysWY/L3xb05vO6JKWrWQlJ5bH1BcMxo6
    MccQA7t04XzR+u4aX1rHxAsxnc9JNgPw5LSbyN7M4pE9J9pi2F5gGlyvltL1JSDg
    JHrLcOpwIrXuKGD1pDk8vBHzz8xuQT+VOb1lBRXO61XK5Q8olEqy9jErEjIRYLOb
    IXW8+FcTJrnV1IjUZbpW3GP4kRGlwgwEmMM/ggHbT98FQbmO1Aaa4ArETZilfjfY
    KUsVuSRgU0BY8Kkq18dI/qvBngebV/CECnyDb98FUYhOAwuJF+vSmS9HSBXzyrnw
    axyuUu1YupBn4stOXzll2Z7BimBTVNL0FdKDWFowDmDF6jS8F1Cx7AGNOrSLYeYm
    pmRX+bjYxZo50mEgJVQ05OfIdLFfpst2gmiAiLauIqjlzKvNhYUerD3Y9cPKkt8O
    i22gbUKbDS+YWXa8GPPObZU=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: signing-cabundle
  namespace: kubernetes-service-ca

